name: my_testscript
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: run the script
      run: chmod u+x 2zadanie 3zadanie 4zadanie
      
  test2:
    runs-on: ubuntu-latest
    steps:
    - name: run the script
      run: |-
        bash 2zadanie
        bash 3zadanie
        bash 4zadanie
