name: my_testscript
on: 
  push:
    branches:
      - master
jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: run the script
jobs:
  test2:
    runs-on: ubuntu-latest
    steps:
    - run: |-
        chmod u+x zadanie 2zadanie 3zadanie 4zadanie
        ./zadanie
        ./2zadanie
        ./3zadanie
        ./4zadanie
